export const IS_IOS_RUNTIME_ENV =
  typeof navigator !== 'undefined' && /iPad|iPhone|iPod/.test(navigator.userAgent);
export const IS_ANDROID_RUNTIME_ENV =
  typeof navigator !== 'undefined' && /Android/.test(navigator.userAgent);
export const IS_CAPACITOR_NATIVE_RUNTIME =
  typeof window !== 'undefined' && Boolean((window as any).Capacitor?.isNativePlatform?.());
export const IS_IOS_WEB_RUNTIME =
  IS_IOS_RUNTIME_ENV && !IS_CAPACITOR_NATIVE_RUNTIME;

export const CHANNEL_NATIVE_TICK_MS_IOS = 55;
export const CHANNEL_NATIVE_TICK_MS_ANDROID = 90;
export const CHANNEL_NATIVE_TICK_MS_DEFAULT = 70;
export const CHANNEL_IOS_STARTUP_HIGH_RATE_WINDOW_MS = 1200;
export const CHANNEL_IOS_STARTUP_BACKWARD_GUARD_WINDOW_MS = 900;
export const CHANNEL_IOS_STARTUP_BACKWARD_GUARD_MAX_MS = 42;
export const CHANNEL_IOS_STARTUP_BACKWARD_GUARD_BYPASS_MS = 220;
export const CHANNEL_START_RAMP_SEC = IS_IOS_WEB_RUNTIME ? 0.008 : IS_IOS_RUNTIME_ENV ? 0.012 : IS_ANDROID_RUNTIME_ENV ? 0.01 : 0.008;
export const CHANNEL_PAUSE_FADE_SEC = IS_IOS_WEB_RUNTIME ? 0.014 : IS_IOS_RUNTIME_ENV ? 0.022 : IS_ANDROID_RUNTIME_ENV ? 0.018 : 0.014;
export const CHANNEL_PAUSE_FINALIZE_DELAY_MS = Math.ceil(CHANNEL_PAUSE_FADE_SEC * 1000) + 8;
export const CHANNEL_STOP_FAST_FADE_SEC = IS_IOS_WEB_RUNTIME ? 0.01 : IS_IOS_RUNTIME_ENV ? 0.016 : IS_ANDROID_RUNTIME_ENV ? 0.012 : 0.01;
export const CHANNEL_STOP_FAST_FINALIZE_DELAY_MS = Math.ceil(CHANNEL_STOP_FAST_FADE_SEC * 1000) + 8;
export const CHANNEL_SEEK_FADE_SEC = 0.01;
export const CHANNEL_SEEK_DELAY_MS = 15;
export const CHANNEL_IOS_HOTCUE_SEEK_FADE_SEC = IS_IOS_WEB_RUNTIME ? 0.004 : 0.006;
export const CHANNEL_IOS_HOTCUE_SEEK_DELAY_MS = IS_IOS_WEB_RUNTIME ? 2 : 6;
export const CHANNEL_IOS_HOTCUE_COALESCE_MS = IS_IOS_WEB_RUNTIME ? 16 : 42;
export const CHANNEL_HOTCUE_TRIGGER_COOLDOWN_MS = IS_IOS_RUNTIME_ENV
  ? (IS_CAPACITOR_NATIVE_RUNTIME ? 70 : 28)
  : (IS_CAPACITOR_NATIVE_RUNTIME ? 55 : 30);
